### ISSUE TITLE
configure.ac:19: error: possibly undefined macro: AC_PROG_LIBTOOL

### ISSUE THREAD

**Issue by jmorales** [jmervine/httperf#1]
Trying to install it on debian 6, doing "autoreconf -i"  gives me that error.

**Comment by coder03** [comment]
Hi everyone, I tried following command on my ubuntu.
1. form build directory: autoconf ../httperf/configure.ac
     If you get error, then you have to install autoconf.
2. Above command will print a lot of things on console and end up with the following error: 
     ../httperf/configure.ac:13: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.

If anyone knows how to solve please update this thread.

**Comment by gotnix** [comment]
I generate the `configure` file in CentOS 6.5, steps by follow:
```
yum -y install gcc make binutils autoconf automake libtool.x86_64 libtool-ltdl.x86_64
cd SRCDIR
mkdir m4
autoreconf -i
```

It will create the `configure` file, then run configure, make, make install:

```
yum -y install openssl-devel.x86_64 openssl-static.x86_64
export CFLAGS='-O2 -g -pipe -Wall -fexceptions -fno-strict-aliasing -fstack-protector -m64 -mtune=generic' \
CPPFLAGS="-I/usr/include" \
LDFLAGS="-L/usr/lib64"
./configure --prefix=/opt/app/httperf
make -j4 && make install
```
